# Generated by Django 6.1.1 on 2026-10-02 16:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shiftlog_admin',
            },
        ),
    ]
