# Generated by Django 6.1.1 on 2026-10-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftlog', '0002_adminmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
